# TravisCI configuration for wprig/wprig

_shared_script_install_wordpress_test_suite: &script_install_wordpress_test_suite |
  if [[ "$WP_VERSION" == "latest" ]]; then
    curl -s http://api.wordpress.org/core/version-check/1.7/ > /tmp/wp-latest.json
    WP_VERSION=$(grep -o '"version":"[^"]*' /tmp/wp-latest.json | sed 's/"version":"//')
  fi
  THEME_SLUG=$(basename $(pwd))
  export WP_DEVELOP_DIR=/tmp/wordpress/
  git clone --depth=50 --branch="$WP_VERSION" git://develop.git.wordpress.org/ /tmp/wordpress
  cd ..
  cp -r "$THEME_SLUG" "/tmp/wordpress/src/wp-content/themes/$THEME_SLUG"
  cd /tmp/wordpress/
  cp wp-tests-config-sample.php wp-tests-config.php
  sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
  sed -i "s/yourusernamehere/travis/" wp-tests-config.php
  sed -i "s/yourpasswordhere//" wp-tests-config.php
  mysql -e "CREATE DATABASE wordpress_tests;" -u root
  cd "/tmp/wordpress/src/wp-content/themes/$THEME_SLUG"

_shared_script_php_lint: &script_php_lint |
  find -L . -name '*.php' -not -path '*/vendor/*' -print0 | xargs -0 -n 1 -P 4 -- php -l

if: "branch = master"

language: "php"
os:
  - "linux"
dist: "bionic"

jobs:
  fast_finish: true
  include:
    - name: "Lint, Unit tests, Gulp - PHP 7.3"
      php: "7.3"
      install:
        - "composer install"
        - "npm install"
        - "wget https://develop.svn.wordpress.org/trunk/.jshintrc"
      script:
        - *script_php_lint
        - "composer run-script phpcs-dev"
        - "npx eslint ."
        - "composer run-script phpunit-dev"
        - "npm run lint:gulp"
        - "npm run test:gulp"

    - name: "Unit tests - PHP 7.0"
      dist: "xenial"
      php: "7.0"
      install:
        - "composer install"
      script:
        - *script_php_lint
        - "composer run-script phpunit-dev"

    - name: "Unit tests - PHP 8.0"
      php: "8.0"
      install:
        - "composer install"
      script:
        - *script_php_lint
        - "composer run-script phpunit-dev"

    - name: "WP latest - PHP 7.3"
      php: "7.3"
      env: "WP_VERSION=latest"
      install:
        - "composer install"
        - *script_install_wordpress_test_suite
      script:
        - "composer run-script phpunit-integration-dev"

    - name: "WP 4.5 - PHP 7.3"
      php: "7.3"
      env: "WP_VERSION=4.5"
      install:
        - "composer install"
        - *script_install_wordpress_test_suite
      script:
        - "composer run-script phpunit-integration-dev"

    - name: "WP trunk - PHP 7.3"
      php: "7.3"
      env: "WP_VERSION=master"
      install:
        - "composer install"
        - *script_install_wordpress_test_suite
      script:
        - "composer run-script phpunit-integration-dev"

  allow_failures:
    - name: "Unit tests - PHP 8.0"
    - name: "WP trunk - PHP 7.3"

services:
  - "mysql"

cache:
  npm: true
  directories:
    - "${HOME}/.composer/cache"

before_install:
  - "phpenv config-rm xdebug.ini"
  - "composer validate --strict"

notifications:
  email: false
